name: Bug Report
description: Report a reproducible bug or unexpected behavior
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the information below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clearly describe the issue, what you expected, and what happened instead.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. 
        2. 
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: mwe
    attributes:
      label: Minimal Reproducible Example
      render: cpp
      placeholder: |
        // Add minimal code to reproduce
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, compiler, Arrow/Spark versions, etc.
      placeholder: e.g., Ubuntu 22.04, GCC 12.1, Arrow 16.0.0

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Paste any stack traces, screenshots, or error output.
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
